### ISSUE TITLE
Closing parallel (2) tasks via `Escape` key only closes the second task

### ISSUE THREAD

**Issue by nobrayner** [Kevnz/isom#2]
Given the following task definition:
```json
{
  "dev:web": [
    "npx webpack serve --config ./src/webpack/dev.config.js --mode development",
    "npx start-storybook -p 6006"
  ],
}
```
That is invoked via yarn:
```json
{
  // ...snip
  "scripts": {
     // ...snip
    "dev:web": "isom dev:web"
  }
}
```

Pressing the `Escape` key to quit the tasks only kills the _second_ task:

Checking for processes running on the used ports (8080 for webpack, 6006 for storybook) afterwards shows webpack is still running (can also be seen by trying to run webpack again afterwards - complains about port being in use):
```
❯ lsof -i :8080 | grep LISTEN
node    63136 nobrayner   25u  IPv4 0x6a0d6c02da3cdebf      0t0  TCP localhost:http-alt (LISTEN)

❯ lsof -i :6006 | grep LISTEN

```

**Comment by Kevnz** [comment]
This is fixed in the latest release
